### ISSUE TITLE
Close image file handle

### ISSUE THREAD

**Issue by mleise** [Whiplash141/Whips-Image-Converter#14]
Currently when you convert images you actively work on in Photoshop/GIMP/Inkskape/MS Paint, you can often not overwrite files. I didn't look at the code, but suspect that system handles are left for the garbage collector to close. If you could actively close it as soon as the image data is read, that would help with iterating over a design.
A "Reload" button next to "Browse" would also be useful in that context.

**Comment by Whiplash141** [comment]
@mleise Should be implemented. Try out version 1.2.3.2 :)

**Comment by mleise** [comment]
Wait what? I thought this project was abandoned. Thank you, I guess.
