### ISSUE TITLE
Ability to paste images into converter from clipboard

### ISSUE THREAD

**Issue by Quartofel** [Whiplash141/Whips-Image-Converter#25]
I hope that feature requests aren't too annoying. Shame on me if they are.
That being said...
Ability to feed the tool with an image stored in clipboard would really help with converting a lot of images on the fly. 

I tend to have a lot of LCDs in one file I constantly tinker with, and ability to just select, copy, paste and convert instead of cropping the image, saving it as a a file and then navigating through file browser to select the file to convert would be delightful.

**Comment by Whiplash141** [comment]
Release v1.2.5.0 has implemented this feature
